# Generated by Django 3.1.1 on 2020-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_room_patient_record',
            name='room_num',
            field=models.IntegerField(unique=True),
        ),
    ]
