# Generated by Django 3.1.1 on 2020-09-26 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200926_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_bloodpressure',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient_temperature',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
